services:
  # Backend Server
  - type: web
    name: party-game-server
    env: node
    region: frankfurt  # Of: oregon, singapore
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001

  # Frontend Static Site
  - type: web
    name: party-game-client
    env: static
    region: frankfurt
    buildCommand: npm install && npm run build
    staticPublishPath: client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
